import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
const envPath=new URL('../.env.local',import.meta.url);
const env=Object.fromEntries(readFileSync(envPath,'utf8').split(/\r?\n/).filter(l=>l&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i),l.slice(i+1)];}));
for(const key of ['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','ADMIN_CODE','ADMIN_USER_ID'])if(!env[key])throw Error(`Missing ${key} in gift-app/.env.local`);
const db=createClient(env.SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const sessions=new Map(),port=Number(env.ADMIN_PORT||5174),origin=`http://127.0.0.1:${port}`;
const htmlEscape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page=(title,body)=>`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${htmlEscape(title)} · Gift Console</title><style>body{font:16px system-ui;background:#faf6f0;color:#453b35;margin:0}main{max-width:900px;margin:36px auto;padding:0 20px}h1{font-size:32px}section{background:#fff;border:1px solid #eee1d5;border-radius:14px;padding:24px;margin:18px 0}input,textarea,button,select{font:inherit;padding:10px;border-radius:8px;border:1px solid #ddcfc4}input,textarea,select{width:100%;box-sizing:border-box;margin:5px 0 13px}button{background:#d8907d;color:#fff;border:0;cursor:pointer}img{max-width:100%;max-height:340px;border-radius:8px}figure{display:inline-block;vertical-align:top;width:200px;margin:8px}figure img{width:200px;height:160px;object-fit:cover}small{color:#8c8177}form{margin:12px 0}nav{display:flex;justify-content:space-between;align-items:center}</style></head><body><main>${body}</main></body></html>`;
function reply(res,status,body,headers={}){res.writeHead(status,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; img-src 'self'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'",...headers});res.end(body);}
function checked(result){if(result.error)throw result.error;return result.data;}
function compare(a,b){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
async function form(req){let data='';for await(const chunk of req){data+=chunk;if(data.length>20000)throw Error('表单太长');}return Object.fromEntries(new URLSearchParams(data));}
async function embed(input){if(!env.EMBEDDING_API_KEY)throw Error('缺少 EMBEDDING_API_KEY');const response=await fetch(env.EMBEDDING_API_URL||'https://api.openai.com/v1/embeddings',{method:'POST',headers:{Authorization:`Bearer ${env.EMBEDDING_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.EMBEDDING_MODEL||'text-embedding-3-small',input}),signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Embedding 服务无法使用');const data=await response.json();if(!Array.isArray(data.data?.[0]?.embedding))throw Error('Embedding 返回无效');return data.data[0].embedding;}
async function dashboard(){const games=checked(await db.from('gift_games').select('*').order('created_at',{ascending:false}).limit(10));const photos=checked(await db.from('gift_photos').select('*').is('deleted_at',null).order('created_at',{ascending:false}).limit(100));const guesses=checked(await db.from('gift_guesses').select('text,score,is_correct,created_at').order('created_at',{ascending:false}).limit(100));const active=games.find(g=>g.status==='active');const current=games.find(g=>g.status!=='archived');const secret=current?checked(await db.from('gift_game_secrets').select('answer,aliases,reveal_text').eq('game_id',current.id).single()):null;
return page('管理台',`<nav><h1>🎁 Gift 本地控制台</h1><form method="post" action="/logout"><button>退出</button></form></nav><small>只在本机运行 · 相册图片不会由 GitHub Pages 返回</small><section><h2>当前礼物</h2>${current?`<p>${htmlEscape(current.title)} · ${htmlEscape(current.status)}</p><p>谜底：${htmlEscape(secret.answer)}</p><p>同义词：${htmlEscape(secret.aliases.join('、'))}</p>${active?`<form method="post" action="/reveal"><input type="hidden" name="game" value="${htmlEscape(active.id)}"><button>现在揭晓</button></form>`:''}`:'<p>还没有设置礼物。</p>'}</section><section><h2>准备下一份礼物</h2><form method="post" action="/create"><label>游戏名称<input name="title" required maxlength="80" value="下一份惊喜"></label><label>谜底<input name="answer" required maxlength="80"></label><label>同义答案（逗号分隔）<input name="aliases" maxlength="2000"></label><label>揭晓时的话<textarea name="reveal" required maxlength="2000"></textarea></label><label>揭晓图片<select name="photo"><option value="">暂不设置</option>${photos.map((p,i)=>`<option value="${htmlEscape(p.id)}">照片 ${i+1} · ${htmlEscape(new Date(p.created_at).toLocaleDateString('zh-CN'))}</option>`).join('')}</select></label><button>保存礼物</button></form></section><section><h2>私人相册 · ${photos.length} 张</h2>${photos.length?photos.map(p=>`<figure><img src="/photo/${htmlEscape(p.id)}" alt="私人照片" loading="lazy"><figcaption><small>${htmlEscape(new Date(p.created_at).toLocaleString('zh-CN'))}</small><form method="post" action="/delete"><input type="hidden" name="id" value="${htmlEscape(p.id)}"><button>删除</button></form></figcaption></figure>`).join(''):'<p>还没有照片。</p>'}</section><section><h2>猜测记录</h2>${guesses.map(g=>`<p>${htmlEscape(g.text)} · ${Number(g.score).toFixed(0)}% · ${g.is_correct?'猜中':'未中'} · <small>${htmlEscape(new Date(g.created_at).toLocaleString('zh-CN'))}</small></p>`).join('')||'<p>还没有猜测。</p>'}</section>`);}
const server=createServer(async(req,res)=>{try{const url=new URL(req.url||'/',origin);if(req.method==='POST'&&req.headers.origin!==origin)return reply(res,403,page('拒绝','来源不正确'));
const cookie=req.headers.cookie?.match(/(?:^|; )gift_admin=([a-f0-9]{64})(?:;|$)/)?.[1];const authenticated=cookie&&sessions.has(cookie)&&sessions.get(cookie)>Date.now();
if(url.pathname==='/login'&&req.method==='POST'){const body=await form(req);if(!compare(String(body.code||''),env.ADMIN_CODE))return reply(res,401,page('再试一次','<h1>暗号不对</h1><a href="/">返回</a>'));const token=randomBytes(32).toString('hex');sessions.set(token,Date.now()+8*3600000);return reply(res,303,'',{Location:'/', 'Set-Cookie':`gift_admin=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`});}
if(!authenticated)return reply(res,200,page('进入',`<section><h1>这片小天地的管理员是谁呀？</h1><form method="post" action="/login"><input type="password" name="code" placeholder="管理员暗号" required><button>进入本地控制台</button></form></section>`));
if(url.pathname==='/logout'&&req.method==='POST'){sessions.delete(cookie);return reply(res,303,'',{Location:'/', 'Set-Cookie':'gift_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'});}
if(url.pathname.startsWith('/photo/')&&req.method==='GET'){const id=url.pathname.slice(7);if(!/^[a-f0-9-]{36}$/.test(id))throw Error('ID 无效');const photo=checked(await db.from('gift_photos').select('storage_path').eq('id',id).is('deleted_at',null).single());const blob=checked(await db.storage.from('gift-private').download(photo.storage_path));res.writeHead(200,{'Content-Type':'image/jpeg','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});return res.end(Buffer.from(await blob.arrayBuffer()));}
if(url.pathname==='/create'&&req.method==='POST'){const b=await form(req);const title=String(b.title||'').trim(),answer=String(b.answer||'').trim(),reveal=String(b.reveal||'').trim(),aliases=String(b.aliases||'').split(/[，,]/).map(x=>x.trim()).filter(Boolean);if(!title||!answer||!reveal||title.length>80||answer.length>80||reveal.length>2000)throw Error('表单无效');const vector=await embed(answer);checked(await db.rpc('gift_create',{p_user:env.ADMIN_USER_ID,p_id:randomUUID(),p_title:title,p_answer:answer,p_aliases:aliases,p_embedding:vector,p_model:env.EMBEDDING_MODEL||'text-embedding-3-small',p_reveal:reveal,p_photo:b.photo||null}));return reply(res,303,'',{Location:'/'});}
if(url.pathname==='/reveal'&&req.method==='POST'){const b=await form(req);checked(await db.from('gift_games').update({status:'revealed'}).eq('id',b.game).eq('status','active'));return reply(res,303,'',{Location:'/'});}
if(url.pathname==='/delete'&&req.method==='POST'){const b=await form(req);const photo=checked(await db.from('gift_photos').select('storage_path').eq('id',b.id).is('deleted_at',null).single());checked(await db.from('gift_photos').update({deleted_at:new Date().toISOString()}).eq('id',b.id));checked(await db.storage.from('gift-private').remove([photo.storage_path]));return reply(res,303,'',{Location:'/'});}
if(url.pathname==='/'&&req.method==='GET')return reply(res,200,await dashboard());return reply(res,404,page('找不到','<h1>找不到这个页面</h1>'));
}catch(e){console.error('local console error',e?.message);return reply(res,500,page('出错了',`<h1>操作未完成</h1><p>${htmlEscape(e?.message||'未知错误')}</p><a href="/">返回</a>`));}});
server.listen(port,'127.0.0.1',()=>console.log(`Gift console: ${origin}`));
