import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
import {LockKeyhole,LogOut,UploadCloud,X,CheckCircle2,AlertCircle} from 'lucide-react';
import './style.css';
declare global {interface Window {GIFT_CONFIG?:{supabaseUrl:string;publishableKey:string}}}
type Guess={id:string;text:string;score:number;is_correct:boolean;created_at:string};
type Reveal={answer:string;text:string;image:string|null};
type Whisper={id:string;message:string;reply:string|null;status:string;created_at:string};
function Toast({message,error,onClose}:{message:string;error:boolean;onClose:()=>void}){return <div className={`toast ${error?'toast-error':''}`} role={error?'alert':'status'}>{error?<AlertCircle size={18}/>:<CheckCircle2 size={18}/>}<span>{message}</span><button type="button" onClick={onClose} aria-label="关闭提示"><X size={16}/></button></div>;}
function WhisperHistory({items}:{items:Whisper[]}){return items.length?<details className="whisper"><summary>我们的小纸条 · {items.length}</summary>{items.map(w=><div key={w.id}><small>{new Date(w.created_at).toLocaleString('zh-CN')}</small><p>你：{w.message}</p><p className="whisper-reply">{w.reply||(w.status==='failed'?'这次小纸条没写好。':'小纸条还在路上。')}</p></div>)}</details>:null;}
type PastGame={id:string;title:string;status:string;created_at:string;guesses:Guess[];whispers:Whisper[];reveal:Reveal|null};
type GameState={member:{balance:number};game:null|{id:string;title:string;status:string};guesses:Guess[];whispers:Whisper[];reveal:Reveal|null;history:PastGame[];subscription:{email:string;status:string}|null;mailReady:boolean;teaseReady:boolean};
const cfg=window.GIFT_CONFIG;
const supabase:SupabaseClient|null=cfg?.supabaseUrl&&cfg.publishableKey?createClient(cfg.supabaseUrl,cfg.publishableKey):null;
const messages:Record<string,string>={TEASE_UNAVAILABLE:'悄悄话暂时卡壳啦，等会儿再来逗逗它。',TEASE_LIMIT:'今天的小纸条写完啦，明天再来撒个娇？',UNAUTHORIZED:'咦，暗号好像不对，再悄悄试一次？',FORBIDDEN:'这扇小门暂时打不开。',NO_CREDITS:'爱心不够啦，送我一张新照片或视频，再攒 5 枚吧。',GAME_CHANGED:'礼物刚刚有了变化，刷新一下看看吧。',RATE_LIMITED:'慢一点点，我们等会儿再试。',EMBEDDING_UNAVAILABLE:'猜测小助手暂时走神了，待会儿再来。',INVALID_IMAGE:'这张照片没收好，换一张试试？',INVALID_MEDIA:'视频请选 10 MB 以内的 MP4 或 WebM，照片请选 JPG、PNG 或 WebP。',FACE_REFERENCE_MISSING:'管理员还没有设置参考人物。',FACE_REFERENCE_CHANGED:'参考照片刚换好，再试一次吧。',FACE_MISMATCH:'这份照片里没有认出指定的人，换一张试试？',FACE_UNAVAILABLE:'人脸小助手暂时走神了，请稍后再试。',UPLOAD_EXPIRED:'照片上传超时啦，再选一次吧。',MAIL_UNAVAILABLE:'信暂时没寄出去，稍后再试试。',LINK_EXPIRED:'这封信里的链接已经过期啦。'};
function errorText(error:unknown){const raw=error instanceof Error?error.message:String(error);return Object.entries(messages).find(([key])=>raw.includes(key))?.[1]||'暂时无法完成，请稍后再试。';}
async function call(action:string,data:Record<string,unknown>={}){if(!supabase||!cfg)throw Error('NOT_CONFIGURED');const {data:session}=await supabase.auth.getSession();if(!session.session)throw Error('UNAUTHORIZED');const response=await fetch(`${cfg.supabaseUrl}/functions/v1/gift-api`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.session.access_token}`,apikey:cfg.publishableKey},body:JSON.stringify({action,...data})});const result=await response.json();if(!response.ok)throw Error(result.error||'SERVER_ERROR');return result;}
function App(){const [ready,setReady]=useState(false),[state,setState]=useState<GameState|null>(null),[code,setCode]=useState(''),[guess,setGuess]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [interaction,setInteraction]=useState(''),[whisper,setWhisper]=useState(''),[teaseBusy,setTeaseBusy]=useState(false),[mode,setMode]=useState<'guess'|'whisper'>('guess');
 useEffect(()=>{setInteraction('');setWhisper('');setError('');},[state?.game?.id]);
 useEffect(()=>{if(!notice&&!error)return;const timer=window.setTimeout(()=>{setNotice('');setError('');},error?8000:4500);return()=>window.clearTimeout(timer);},[notice,error]);
 const askWhisper=async(e:React.FormEvent)=>{e.preventDefault();if(!state?.game||teaseBusy)return;setTeaseBusy(true);setError('');setNotice('');try{const result=await call('tease',{gameId:state.game.id,message:interaction});setWhisper(result.reply);setInteraction('');await refresh();setNotice(result.duplicate?'这句小纸条已经收好了。':'小纸条收好啦 · 消耗 1 枚爱心');}catch(error){setError(errorText(error));try{await refresh();}catch{}}finally{setTeaseBusy(false);}};
 const refresh=async()=>setState(await call('state') as GameState);
 useEffect(()=>{if(!supabase){setReady(true);return;}const params=new URLSearchParams(location.search),kind=params.get('subscription'),token=params.get('token');if(kind&&token){history.replaceState(null,'',location.pathname);fetch(`${cfg!.supabaseUrl}/functions/v1/gift-api`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg!.publishableKey},body:JSON.stringify({action:'subscription-link',kind,token})}).then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error);setNotice(kind==='confirm'?'收到啦！有新惊喜时，我会悄悄写信给你。':'好呀，先不写信打扰你啦。');}).catch(e=>setError(errorText(e))).finally(()=>supabase.auth.getSession().then(async({data})=>{if(data.session)try{await refresh();}catch{await supabase.auth.signOut();}setReady(true);}));}else{supabase.auth.getSession().then(async({data})=>{if(data.session)try{await refresh();}catch{await supabase.auth.signOut();}setReady(true);});}const {data:subscription}=supabase.auth.onAuthStateChange((_event,session)=>{if(!session)setState(null);});return()=>subscription.subscription.unsubscribe();},[]);
 const run=async(task:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await task();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const enter=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{const response=await fetch(`${cfg!.supabaseUrl}/functions/v1/gift-api`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg!.publishableKey},body:JSON.stringify({action:'enter',code})});const result=await response.json();if(!response.ok)throw Error(result.error);const {error:e}=await supabase!.auth.setSession({access_token:result.access_token,refresh_token:result.refresh_token});if(e)throw e;setCode('');await refresh();});};
 const upload=(file:File|null)=>{if(!file)return;run(async()=>{
  let payload:Blob=file;let mime=file.type;
  if(mime.startsWith('video/')){if(!['video/mp4','video/webm'].includes(mime)||file.size>10*1024*1024)throw Error('INVALID_MEDIA');}
  else {
   if(!['image/jpeg','image/png','image/webp'].includes(mime)||file.size>20*1024*1024)throw Error('INVALID_IMAGE');
   const image=await createImageBitmap(file);
   try {const scale=Math.min(1,1200/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext('2d');if(!context)throw Error('INVALID_IMAGE');context.drawImage(image,0,0,canvas.width,canvas.height);payload=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('INVALID_IMAGE')),'image/jpeg',.85));mime='image/jpeg';}finally{image.close();}
  }
  const intent=await call('media-upload-intent',{mime});
  const {error:e}=await supabase!.storage.from('gift-private').uploadToSignedUrl(intent.path,intent.token,payload,{contentType:mime});if(e)throw e;
  const result=await call('finalize-media',{id:intent.id});await refresh();
  setNotice(result.duplicate?'这份内容我已经收好啦。':'校验通过，已经悄悄收好。多了 5 枚爱心 ♡');
 });};
 const submit=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{if(!state?.game)return;const result=await call('guess',{gameId:state.game.id,text:guess});setGuess('');await refresh();setNotice(result.duplicate?'这个词我们猜过啦，换个想法？不重复扣爱心。':result.guess.is_correct?'猜中啦！快来拆礼物 ♡':`接近度 ${Math.round(result.guess.score)}%，再猜猜？`);});};
 const subscribe=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{const result=await call('subscribe',{email});await refresh();setNotice(result.status==='active'?'这个邮箱已经在我的小本本上啦。':result.status==='pending'?'给你寄了封确认信，去邮箱里点一下就好 ♡':result.status==='cooldown'||result.status==='limit'?'换邮箱太快啦，等一会儿再试试。':'给你寄了封确认信，去邮箱里点一下就好 ♡');});};
 const unsubscribe=()=>run(async()=>{await call('unsubscribe');await refresh();setNotice('好呀，先不写信打扰你啦。');});
 return <div className="gift-app"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><header className="topbar"><a className="brand" href="/miscellaneous"><span className="brand-mark">✳</span><span>shiyan's little corner</span></a><span className="topbar-note">a tiny place for us two ♡</span></header>
 {!ready?<main className="shell"><section className="paper gate"><p>正在为你开门…</p></section></main>:
 !cfg?.supabaseUrl||!cfg.publishableKey?<main className="shell"><section className="paper gate"><h1>小惊喜正在整理中</h1><p>过一会儿再来敲敲门，好吗？</p></section></main>:
 !state?<main className="shell"><section className="paper gate"><div className="gift-illustration"><div className="gift-stars">✦ &nbsp; ✧ &nbsp; ✦</div><div className="gift-box">✳</div></div><span className="eyebrow">JUST FOR YOU</span><h1>嘘，这里藏着一个小秘密。<br/><em>来的人是谁呀？</em></h1><p className="intro">说出我们约好的暗号，<br/>看看门后藏着什么。</p><form className="form" onSubmit={enter}><label>暗号<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="off" placeholder="悄悄告诉我" required/></label><button className="primary" disabled={busy}>推开小门 <span>↗</span></button></form><p className="gate-foot"><LockKeyhole size={13}/> 这里的秘密，只和你分享</p></section><p className="footer">made with ♡ · a little game for two</p></main>:
 <><main className="shell"><div className="app-head"><div><span className="eyebrow">OUR LITTLE SECRET</span><h1>{state.game?.title||'等待下一份惊喜'}</h1><p className="intro small">{state.game?'礼物藏好啦，来猜猜，或讨一句悄悄话。':'上一份已收进回忆里，下一份正在偷偷准备。'}</p></div><div className="wallet"><span>🩷 爱心</span><div><strong>{state.member.balance}</strong><small>枚</small></div><button onClick={()=>supabase?.auth.signOut()} aria-label="退出专属空间"><LogOut size={14}/>退出</button></div></div>
 <div className={`action-grid ${state.game?'':'waiting-grid'}`}>
 {state.game&&<section className="paper play-card"><div className="play-tabs" role="tablist" aria-label="互动方式" onKeyDown={e=>{if(!state.teaseReady||!["ArrowLeft","ArrowRight","Home","End"].includes(e.key))return;e.preventDefault();const next=e.key==="Home"?"guess":e.key==="End"?"whisper":mode==="guess"?"whisper":"guess";setMode(next);e.currentTarget.querySelector<HTMLButtonElement>(`#${next}-tab`)?.focus();}}><button id="guess-tab" role="tab" tabIndex={mode==='guess'?0:-1} aria-selected={mode==='guess'} aria-controls="guess-panel" onClick={()=>setMode('guess')}>猜礼物 <small>2 枚 / 次</small></button>{state.teaseReady&&<button id="whisper-tab" role="tab" tabIndex={mode==='whisper'?0:-1} aria-selected={mode==='whisper'} aria-controls="whisper-panel" onClick={()=>setMode('whisper')}>悄悄话 <small>1 枚 / 次</small></button>}</div>
 {mode==='guess'?<div id="guess-panel" role="tabpanel" aria-labelledby="guess-tab" className="play-body"><h2>你想到什么啦？</h2><p className="muted">写下一个答案，看看离惊喜有多近。</p><form className="guess-form" onSubmit={submit}><input aria-label="猜测的礼物" value={guess} onChange={e=>setGuess(e.target.value)} maxLength={80} placeholder="比如：耳机、一场旅行…" required/><button className="primary" disabled={busy||teaseBusy||state.member.balance<2}> {busy?'猜测中…':'猜一下'} <span>↗</span></button></form>{state.member.balance<2&&<p className="hint">需要 2 枚爱心，留张照片或视频就能补充。</p>}{state.guesses[0]&&<div className="last-guess"><span>上次猜：{state.guesses[0].text}</span><strong>{Math.round(state.guesses[0].score)}% 接近</strong></div>}</div>:<div id="whisper-panel" role="tabpanel" aria-labelledby="whisper-tab" className="play-body"><h2>撒个娇，试试看？</h2><p className="muted">可以打趣，可以撒娇，谜底可不能直接偷看。</p><form className="whisper-form" onSubmit={askWhisper}><input value={interaction} onChange={e=>setInteraction(e.target.value)} placeholder="拜托拜托，透露一点点嘛…" aria-label="想对礼物盒说的话" maxLength={160} required/><button className="primary" disabled={teaseBusy||busy||state.member.balance<1}>{teaseBusy?'写纸条中…':'问一句'} <span>↗</span></button></form>{whisper&&<p className="whisper-reply" role="status">{whisper}</p>}<p className="hint">没写好不消耗爱心 · 每天最多 20 句 · 记录会收好</p>{state.member.balance<1&&<p className="hint">爱心用完啦，送张照片或视频再来？</p>}</div>}
 </section>}
 <section className="paper upload-card"><div className="card-title"><UploadCloud size={19}/><h2>留一份小日常</h2><span>+5 枚</span></div><p className="muted">新照片或视频通过校验后，送你 5 枚爱心。</p><label className={`upload-area ${busy||teaseBusy?'disabled':''}`}><UploadCloud size={24}/><span>{busy?'正在收好…':'选照片或视频'}</span><small>JPG / PNG / WebP · 视频 ≤10 MB</small><input aria-label="上传照片或视频" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" disabled={busy||teaseBusy} onChange={e=>{upload(e.target.files?.[0]||null);e.currentTarget.value='';}}/></label><p className="hint">新礼物也会送 5 枚，攒着猜或问都可以。</p></section></div>
 {(!!state.guesses.length||!!state.whispers?.length)&&<details className="record-section"><summary>这一份的小记录 <small>{state.guesses.length} 次猜测 · {state.whispers?.length||0} 句悄悄话</small></summary><div className="record-body">{!!state.guesses.length&&<><h3>猜过的答案</h3>{state.guesses.map(g=><div className="guess-row" key={g.id}><span className="guess-word">{g.text}</span><div className="score-track"><i style={{width:`${g.score}%`}}/></div><strong>{Math.round(g.score)}%</strong></div>)}</>}<WhisperHistory items={state.whispers||[]}/></div></details>}
 {!!state.history?.length&&<details className="record-section"><summary>礼物小档案 <small>{state.history.length} 份回忆</small></summary><div className="record-body">{state.history.map(item=><details className="past-game" key={item.id}><summary><span>{item.title}</span><small>{new Date(item.created_at).toLocaleDateString('zh-CN')}</small></summary><div className="past-body">{item.reveal&&<><p>谜底：<strong>{item.reveal.answer}</strong></p>{item.reveal.text&&<p>{item.reveal.text}</p>}{item.reveal.image&&<img className="past-reveal-image" src={item.reveal.image} alt="礼物揭晓"/>}</>}{item.guesses.map(g=><div className="guess-row" key={g.id}><span className="guess-word">{g.text}</span><div className="score-track"><i style={{width:`${g.score}%`}}/></div><strong>{Math.round(g.score)}%</strong></div>)}<WhisperHistory items={item.whispers||[]}/></div></details>)}</div></details>}
 {state.mailReady&&<details className="record-section mail-settings"><summary>新惊喜提醒 <small>{state.subscription?.status==='active'?'已订阅':state.subscription?.status==='pending'?'待邮箱确认':'留个邮箱'}</small></summary><div className="mail-line"><div><small>{state.subscription?.status==='active'?state.subscription.email:state.subscription?.status==='pending'?`确认信已发往 ${state.subscription.email}`:'惊喜藏好时，悄悄写信叫你。'}</small></div>{state.subscription?.status==='active'?<button className="text-button" onClick={unsubscribe} disabled={busy}>取消提醒</button>:<form onSubmit={subscribe}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="你的邮箱" aria-label="订阅邮箱" required/><button type="submit" disabled={busy}>订阅提醒</button></form>}</div></details>}
</main><footer className="footer app-footer"><span>made with ♡ · a little game for two</span><a href="/miscellaneous">← 回到主页</a></footer></>}
 {(error||notice)&&<Toast message={error||notice} error={!!error} onClose={()=>{setError('');setNotice('');}}/>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
