import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
import {Gift,LockKeyhole,LogOut,UploadCloud} from 'lucide-react';
import './style.css';
declare global {interface Window {GIFT_CONFIG?:{supabaseUrl:string;publishableKey:string}}}
type Guess={id:string;text:string;score:number;is_correct:boolean;created_at:string};
type GameState={member:{balance:number};game:null|{id:string;title:string;status:string};guesses:Guess[];reveal:null|{answer:string;text:string;image:string|null}};
const cfg=window.GIFT_CONFIG;
const supabase:SupabaseClient|null=cfg?.supabaseUrl&&cfg.publishableKey?createClient(cfg.supabaseUrl,cfg.publishableKey):null;
const messages:Record<string,string>={UNAUTHORIZED:'暗号似乎不对，再想想？',FORBIDDEN:'这里的门没有打开。',NO_CREDITS:'先分享一张照片，再来猜吧。',GAME_CHANGED:'礼物状态已经更新，请刷新页面。',RATE_LIMITED:'试得太快了，过一会儿再来。',EMBEDDING_UNAVAILABLE:'相似度服务暂时不可用，请稍后再试。',INVALID_IMAGE:'照片无法处理，请换一张。',UPLOAD_EXPIRED:'上传已过期，请重新选照片。'};
function errorText(error:unknown){const raw=error instanceof Error?error.message:String(error);return Object.entries(messages).find(([key])=>raw.includes(key))?.[1]||'暂时无法完成，请稍后再试。';}
async function call(action:string,data:Record<string,unknown>={}){if(!supabase||!cfg)throw Error('NOT_CONFIGURED');const {data:session}=await supabase.auth.getSession();if(!session.session)throw Error('UNAUTHORIZED');const response=await fetch(`${cfg.supabaseUrl}/functions/v1/gift-api`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.session.access_token}`,apikey:cfg.publishableKey},body:JSON.stringify({action,...data})});const result=await response.json();if(!response.ok)throw Error(result.error||'SERVER_ERROR');return result;}
function App(){const [ready,setReady]=useState(false),[state,setState]=useState<GameState|null>(null),[code,setCode]=useState(''),[guess,setGuess]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=async()=>setState(await call('state') as GameState);
 useEffect(()=>{if(!supabase){setReady(true);return;}supabase.auth.getSession().then(async({data})=>{if(data.session)try{await refresh();}catch{await supabase.auth.signOut();}setReady(true);});const {data:subscription}=supabase.auth.onAuthStateChange((_event,session)=>{if(!session)setState(null);});return()=>subscription.subscription.unsubscribe();},[]);
 const run=async(task:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await task();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const enter=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{const response=await fetch(`${cfg!.supabaseUrl}/functions/v1/gift-api`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg!.publishableKey},body:JSON.stringify({action:'enter',code})});const result=await response.json();if(!response.ok)throw Error(result.error);const {error:e}=await supabase!.auth.setSession({access_token:result.access_token,refresh_token:result.refresh_token});if(e)throw e;setCode('');await refresh();});};
 const upload=(file:File|null)=>{if(!file)return;run(async()=>{if(file.size>18*1024*1024)throw Error('INVALID_IMAGE');const image=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext('2d');if(!context)throw Error('INVALID_IMAGE');context.drawImage(image,0,0,canvas.width,canvas.height);image.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('INVALID_IMAGE')),'image/jpeg',0.85));if(blob.size>5*1024*1024)throw Error('INVALID_IMAGE');const intent=await call('upload-intent');const {error:e}=await supabase!.storage.from('gift-private').uploadToSignedUrl(intent.path,intent.token,blob,{contentType:'image/jpeg'});if(e)throw e;const result=await call('finalize-upload',{id:intent.id});await refresh();setNotice(result.duplicate?'这张照片已经收藏过啦，没有重复增加机会。':'照片已悄悄收好，获得 1 次猜测机会 ♡');});};
 const submit=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{if(!state?.game)return;const result=await call('guess',{gameId:state.game.id,text:guess});setGuess('');await refresh();setNotice(result.duplicate?'这个词已经猜过，机会还在。':result.guess.is_correct?'猜对啦！惊喜揭晓 ♡':`接近度 ${Math.round(result.guess.score)}%，再想想？`);});};
 return <div className="gift-app"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><header className="topbar"><a className="brand" href="/miscellaneous"><span className="brand-mark">✳</span><span>shiyan's little corner</span></a><span className="topbar-note">a tiny place for us two ♡</span></header>
 {!ready?<main className="shell"><section className="paper gate"><p>正在打开小天地…</p></section></main>:
 !cfg?.supabaseUrl||!cfg.publishableKey?<main className="shell"><section className="paper gate"><h1>惊喜正在准备中</h1><p>过一会儿再来吧。</p></section></main>:
 !state?<main className="shell"><section className="paper gate"><div className="gift-illustration"><div className="gift-stars">✦ &nbsp; ✧ &nbsp; ✦</div><div className="gift-box">✳</div></div><span className="eyebrow">JUST FOR YOU</span><h1>有一片神秘的小天地。<br/><em>来的人是谁呀？</em></h1><p className="intro">悄悄说出我们约好的暗号，<br/>看看为你准备了什么。</p><form className="form" onSubmit={enter}><label>暗号<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="off" placeholder="悄悄告诉我" required/></label><button className="primary" disabled={busy}>轻轻推开门 <span>↗</span></button></form><p className="gate-foot"><LockKeyhole size={13}/> 只属于我们的小秘密</p>{error&&<p className="error" role="alert">{error}</p>}</section><p className="footer">made with ♡ · a little game for two</p></main>:
 <><main className="shell"><div className="app-head"><div><span className="eyebrow">OUR LITTLE SECRET</span><h1>{state.game?.status==='won'||state.game?.status==='revealed'?'你猜到了！':'猜猜我的礼物'}</h1><p className="intro small">一张照片，换一次猜测机会。慢慢来，惊喜就在附近。</p></div><div className="head-doodle" aria-hidden="true">✺<span>♡</span></div></div><div className="private-bar"><span>♡ 这个角落只属于我们</span><button onClick={()=>supabase?.auth.signOut()} title="退出"><LogOut size={17}/> 退出</button></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 <section className="paper game-hero"><div className="hero-icon"><Gift size={42} strokeWidth={1.6}/></div><span className="eyebrow">THE NEXT SURPRISE</span><h2>{state.game?.title||'下一份惊喜'}</h2><p>{state.game?'它已经准备好了，就等你来发现。':'神秘礼物还在准备中，先留下一张照片吧。'}</p></section>
 {state.game&&['won','revealed'].includes(state.game.status)&&state.reveal?<section className="paper reveal"><span className="eyebrow">SURPRISE, SURPRISE</span><div className="reveal-heart">♡</div><h2>原来是<br/><em>{state.reveal.answer}</em></h2><p>{state.reveal.text}</p>{state.reveal.image&&<img src={state.reveal.image} alt="揭晓礼物"/>}</section>:<><div className="stat-card"><div><span className="stat-label">剩余猜测机会</span><strong>{state.member.balance}</strong></div><span className="stat-spark">✦</span><p>每分享一张新照片，获得一次机会</p></div><div className="action-grid"><section className="paper section-card"><div className="section-heading"><div className="number">01</div><div><h3>先留下一张照片</h3><p>今天的天空、你的笑容，或者任何想让我看到的瞬间。</p></div></div><label className={`upload-area ${busy?'disabled':''}`}><UploadCloud size={26}/><span>点击选择照片</span><small>只有我能在本地相册里看到它</small><input type="file" accept="image/*" disabled={busy} onChange={e=>{upload(e.target.files?.[0]||null);e.currentTarget.value='';}}/></label></section><section className="paper section-card"><div className="section-heading"><div className="number">02</div><div><h3>猜猜是什么</h3><p>想到什么就写什么，越接近，数字越高。</p></div></div><form className="guess-form" onSubmit={submit}><input value={guess} onChange={e=>setGuess(e.target.value)} maxLength={80} placeholder="比如：拍立得、耳机、一场旅行…" required/><button className="primary" disabled={busy||state.member.balance<1||!state.game}>猜一下 <span>↗</span></button></form>{state.member.balance<1&&<p className="hint">还没有机会？先上传一张照片吧 ♡</p>}</section></div></>}
 {!!state.guesses.length&&<section className="history"><div className="list-head"><h3>猜测足迹</h3><span>{state.guesses.length} 次猜测</span></div>{state.guesses.map(g=><div className="guess-row" key={g.id}><span className="guess-word">{g.text}</span><div className="score-track"><i style={{width:`${g.score}%`}}/></div><strong>{Math.round(g.score)}%</strong></div>)}</section>}</main><footer className="footer app-footer"><span>made with ♡ · a little game for two</span><a href="/miscellaneous">← 回到主页</a></footer></>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
