import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
import {Gift,LockKeyhole,LogOut,UploadCloud} from 'lucide-react';
import './style.css';
declare global {interface Window {GIFT_CONFIG?:{supabaseUrl:string;publishableKey:string}}}
type Guess={id:string;text:string;score:number;is_correct:boolean;created_at:string};
type Reveal={answer:string;text:string;image:string|null};
type PastGame={id:string;title:string;status:string;created_at:string;guesses:Guess[];reveal:Reveal|null};
type GameState={member:{balance:number};game:null|{id:string;title:string;status:string};guesses:Guess[];reveal:Reveal|null;history:PastGame[];subscription:{email:string;status:string}|null;mailReady:boolean};
const cfg=window.GIFT_CONFIG;
const supabase:SupabaseClient|null=cfg?.supabaseUrl&&cfg.publishableKey?createClient(cfg.supabaseUrl,cfg.publishableKey):null;
const messages:Record<string,string>={UNAUTHORIZED:'咦，暗号好像不对，再悄悄试一次？',FORBIDDEN:'这扇小门暂时打不开。',NO_CREDITS:'先给我留一张照片，就能继续猜啦。',GAME_CHANGED:'礼物刚刚有了变化，刷新一下看看吧。',RATE_LIMITED:'慢一点点，我们等会儿再试。',EMBEDDING_UNAVAILABLE:'猜测小助手暂时走神了，待会儿再来。',INVALID_IMAGE:'这张照片没收好，换一张试试？',INVALID_MEDIA:'视频请选 10 MB 以内的 MP4 或 WebM，照片请选 JPG、PNG 或 WebP。',FACE_REFERENCE_MISSING:'管理员还没有设置参考人物。',FACE_REFERENCE_CHANGED:'参考照片刚换好，再试一次吧。',FACE_MISMATCH:'这份照片里没有认出指定的人，换一张试试？',FACE_UNAVAILABLE:'人脸小助手暂时走神了，请稍后再试。',UPLOAD_EXPIRED:'照片上传超时啦，再选一次吧。',MAIL_UNAVAILABLE:'信暂时没寄出去，稍后再试试。',LINK_EXPIRED:'这封信里的链接已经过期啦。'};
function errorText(error:unknown){const raw=error instanceof Error?error.message:String(error);return Object.entries(messages).find(([key])=>raw.includes(key))?.[1]||'暂时无法完成，请稍后再试。';}
async function call(action:string,data:Record<string,unknown>={}){if(!supabase||!cfg)throw Error('NOT_CONFIGURED');const {data:session}=await supabase.auth.getSession();if(!session.session)throw Error('UNAUTHORIZED');const response=await fetch(`${cfg.supabaseUrl}/functions/v1/gift-api`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.session.access_token}`,apikey:cfg.publishableKey},body:JSON.stringify({action,...data})});const result=await response.json();if(!response.ok)throw Error(result.error||'SERVER_ERROR');return result;}
function App(){const [ready,setReady]=useState(false),[state,setState]=useState<GameState|null>(null),[code,setCode]=useState(''),[guess,setGuess]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=async()=>setState(await call('state') as GameState);
 useEffect(()=>{if(!supabase){setReady(true);return;}const params=new URLSearchParams(location.search),kind=params.get('subscription'),token=params.get('token');if(kind&&token){history.replaceState(null,'',location.pathname);fetch(`${cfg!.supabaseUrl}/functions/v1/gift-api`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg!.publishableKey},body:JSON.stringify({action:'subscription-link',kind,token})}).then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error);setNotice(kind==='confirm'?'收到啦！有新惊喜时，我会悄悄写信给你。':'好呀，先不写信打扰你啦。');}).catch(e=>setError(errorText(e))).finally(()=>supabase.auth.getSession().then(async({data})=>{if(data.session)try{await refresh();}catch{await supabase.auth.signOut();}setReady(true);}));}else{supabase.auth.getSession().then(async({data})=>{if(data.session)try{await refresh();}catch{await supabase.auth.signOut();}setReady(true);});}const {data:subscription}=supabase.auth.onAuthStateChange((_event,session)=>{if(!session)setState(null);});return()=>subscription.subscription.unsubscribe();},[]);
 const run=async(task:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await task();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const enter=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{const response=await fetch(`${cfg!.supabaseUrl}/functions/v1/gift-api`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg!.publishableKey},body:JSON.stringify({action:'enter',code})});const result=await response.json();if(!response.ok)throw Error(result.error);const {error:e}=await supabase!.auth.setSession({access_token:result.access_token,refresh_token:result.refresh_token});if(e)throw e;setCode('');await refresh();});};
 const upload=(file:File|null)=>{if(!file)return;run(async()=>{
  let payload:Blob=file;let mime=file.type;
  if(mime.startsWith('video/')){if(!['video/mp4','video/webm'].includes(mime)||file.size>10*1024*1024)throw Error('INVALID_MEDIA');}
  else {
   if(!['image/jpeg','image/png','image/webp'].includes(mime)||file.size>20*1024*1024)throw Error('INVALID_IMAGE');
   const image=await createImageBitmap(file);
   try {const scale=Math.min(1,1200/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext('2d');if(!context)throw Error('INVALID_IMAGE');context.drawImage(image,0,0,canvas.width,canvas.height);payload=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('INVALID_IMAGE')),'image/jpeg',.85));mime='image/jpeg';}finally{image.close();}
  }
  const intent=await call('media-upload-intent',{mime});
  const {error:e}=await supabase!.storage.from('gift-private').uploadToSignedUrl(intent.path,intent.token,payload,{contentType:mime});if(e)throw e;
  const result=await call('finalize-media',{id:intent.id});await refresh();
  setNotice(result.duplicate?'这份内容我已经收好啦。':'校验通过，已经悄悄收好。多了 3 次猜礼物的机会 ♡');
 });};
 const submit=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{if(!state?.game)return;const result=await call('guess',{gameId:state.game.id,text:guess});setGuess('');await refresh();setNotice(result.duplicate?'这个词我们猜过啦，换个想法？机会还在。':result.guess.is_correct?'猜中啦！快来拆礼物 ♡':`接近度 ${Math.round(result.guess.score)}%，再猜猜？`);});};
 const subscribe=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{const result=await call('subscribe',{email});await refresh();setNotice(result.status==='active'?'这个邮箱已经在我的小本本上啦。':result.status==='pending'?'给你寄了封确认信，去邮箱里点一下就好 ♡':result.status==='cooldown'||result.status==='limit'?'换邮箱太快啦，等一会儿再试试。':'给你寄了封确认信，去邮箱里点一下就好 ♡');});};
 const unsubscribe=()=>run(async()=>{await call('unsubscribe');await refresh();setNotice('好呀，先不写信打扰你啦。');});
 return <div className="gift-app"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><header className="topbar"><a className="brand" href="/miscellaneous"><span className="brand-mark">✳</span><span>shiyan's little corner</span></a><span className="topbar-note">a tiny place for us two ♡</span></header>
 {!ready?<main className="shell"><section className="paper gate"><p>正在为你开门…</p></section></main>:
 !cfg?.supabaseUrl||!cfg.publishableKey?<main className="shell"><section className="paper gate"><h1>小惊喜正在整理中</h1><p>过一会儿再来敲敲门，好吗？</p></section></main>:
 !state?<main className="shell"><section className="paper gate"><div className="gift-illustration"><div className="gift-stars">✦ &nbsp; ✧ &nbsp; ✦</div><div className="gift-box">✳</div></div><span className="eyebrow">JUST FOR YOU</span><h1>嘘，这里藏着一个小秘密。<br/><em>来的人是谁呀？</em></h1><p className="intro">说出我们约好的暗号，<br/>看看门后藏着什么。</p><form className="form" onSubmit={enter}><label>暗号<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="off" placeholder="悄悄告诉我" required/></label><button className="primary" disabled={busy}>推开小门 <span>↗</span></button></form><p className="gate-foot"><LockKeyhole size={13}/> 这里的秘密，只和你分享</p>{notice&&<p className="notice" role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}</section><p className="footer">made with ♡ · a little game for two</p></main>:
 <><main className="shell"><div className="app-head"><div><span className="eyebrow">OUR LITTLE SECRET</span><h1>{state.game?'猜猜我藏了什么':'等待下一份惊喜'}</h1><p className="intro small">每份礼物可以猜 3 次；送我一张新照片，再加 3 次。</p></div><div className="head-doodle" aria-hidden="true">✺<span>♡</span></div></div><div className="private-bar"><span>♡ 这个角落只属于我们</span><button onClick={()=>supabase?.auth.signOut()} title="退出"><LogOut size={17}/> 退出</button></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 <section className="paper game-hero"><div className="hero-icon"><Gift size={42} strokeWidth={1.6}/></div><span className="eyebrow">THE NEXT SURPRISE</span><h2>{state.game?.title||'等待下一份惊喜'}</h2><p>{state.game?'礼物藏好啦，等你来猜。':'上一份已经好好收进回忆里。下一份，等我偷偷准备好。'}</p></section>
 {state.mailReady&&<section className="mail-line"><div><strong>新惊喜来了，悄悄叫你</strong><small>{state.subscription?.status==='active'?`等我写信给你 · ${state.subscription.email}`:state.subscription?.status==='pending'?`等你点开确认信 · ${state.subscription.email}`:'留个邮箱，礼物藏好时我给你写信。'}</small></div>{state.subscription?.status==='active'?<button className="text-button" onClick={unsubscribe} disabled={busy}>先不提醒</button>:<form onSubmit={subscribe}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="你的邮箱" aria-label="订阅邮箱" required/><button type="submit" disabled={busy}>悄悄提醒我</button></form>}</section>}
 {state.game&&['won','revealed'].includes(state.game.status)&&state.reveal?<section className="paper reveal"><span className="eyebrow">SURPRISE, SURPRISE</span><div className="reveal-heart">♡</div><h2>原来是<br/><em>{state.reveal.answer}</em></h2><p>{state.reveal.text}</p>{state.reveal.image&&<img src={state.reveal.image} alt="揭晓礼物"/>}</section>:<><div className="action-grid"><section className="paper section-card"><div className="section-heading"><div className="number">01</div><div><h3>先给我一张照片</h3><p>{state.game?'送我一张新照片，就能多猜 3 次。':'下一份礼物还在路上，照片可以先悄悄存好。'}</p></div></div><label className={`upload-area ${busy?'disabled':''}`}><UploadCloud size={26}/><span>选一张照片或视频</span><small>匹配参考照片后收好 · 视频最多 10 MB</small><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" disabled={busy} onChange={e=>{upload(e.target.files?.[0]||null);e.currentTarget.value='';}}/></label></section>{state.game&&<section className="paper section-card"><div className="section-heading"><div className="number">02</div><div><h3>猜猜礼物是什么</h3><p>脑海里冒出的第一个答案，就写下来吧。</p></div></div><div className="guess-balance">还剩 <strong>{state.member.balance}</strong> 次机会</div><form className="guess-form" onSubmit={submit}><input value={guess} onChange={e=>setGuess(e.target.value)} maxLength={80} placeholder="比如：拍立得、耳机、一场旅行…" required/><button className="primary" disabled={busy||state.member.balance<1||!state.game}>猜一下 <span>↗</span></button></form>{state.member.balance<1&&<p className="hint">机会用完啦？送我一张新照片就能继续猜 ♡</p>}</section>}</div></>}
 {!!state.guesses.length&&<section className="history"><div className="list-head"><h3>我们猜过的</h3><span>{state.guesses.length} 次猜测</span></div>{state.guesses.map(g=><div className="guess-row" key={g.id}><span className="guess-word">{g.text}</span><div className="score-track"><i style={{width:`${g.score}%`}}/></div><strong>{Math.round(g.score)}%</strong></div>)}</section>}{!!state.history?.length&&<section className="history"><div className="list-head"><h3>礼物小档案</h3><span>{state.history.length} 份</span></div>{state.history.map(item=><details className="past-game" key={item.id}><summary><span>{item.title}</span><small>{new Date(item.created_at).toLocaleDateString('zh-CN')} · {item.guesses.length} 次猜测</small></summary><div className="past-body">{item.reveal&&<><p>谜底：<strong>{item.reveal.answer}</strong></p>{item.reveal.text&&<p>{item.reveal.text}</p>}{item.reveal.image&&<img className="past-reveal-image" src={item.reveal.image} alt="礼物揭晓"/>}</>}{item.guesses.length?item.guesses.map(g=><div className="guess-row" key={g.id}><span className="guess-word">{g.text}</span><div className="score-track"><i style={{width:`${g.score}%`}}/></div><strong>{Math.round(g.score)}%</strong></div>):<p className="muted">这份礼物还没留下猜测呢。</p>}</div></details>)}</section>}</main><footer className="footer app-footer"><span>made with ♡ · a little game for two</span><a href="/miscellaneous">← 回到主页</a></footer></>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
